// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public final class Barbecue {
  private Barbecue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_RegisterMemberRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_RegisterMemberRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_RegisterMemberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_RegisterItensRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_RegisterItensRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_RegisterItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_MembersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_MembersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_MemberRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_MemberRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_ReceiptRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_ReceiptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_VoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_VoucherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_EventResquest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_EventResquest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_br_estudos_grpc_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_br_estudos_grpc_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016barbecue.proto\022\023com.br.estudos.grpc\"^\n" +
      "\025RegisterMemberRequest\022\021\n\tfirstName\030\001 \001(" +
      "\t\022\020\n\010lastName\030\002 \001(\t\022\r\n\005phone\030\003 \001(\t\022\021\n\tev" +
      "entName\030\004 \001(\t\"0\n\026RegisterMemberResponse\022" +
      "\026\n\016welcomeMessage\030\001 \001(\t\"=\n\024RegisterItens" +
      "Request\022\023\n\013description\030\001 \001(\t\022\020\n\010quantity" +
      "\030\002 \001(\005\"1\n\024RegisterItemResponse\022\031\n\021totalI" +
      "tensCreated\030\001 \001(\005\"E\n\017MembersResponse\022\021\n\t" +
      "firstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022\r\n\005pho" +
      "ne\030\003 \001(\t\"\"\n\rMemberRequest\022\021\n\teventName\030\001" +
      " \001(\t\"!\n\016ReceiptRequest\022\017\n\007receipt\030\001 \001(\t\"" +
      "\"\n\017VoucherResponse\022\017\n\007voucher\030\001 \001(\t\"\"\n\rE" +
      "ventResquest\022\021\n\teventName\030\001 \001(\t\"\006\n\004Void2" +
      "\363\003\n\017BarbecueService\022i\n\016registerMember\022*." +
      "com.br.estudos.grpc.RegisterMemberReques" +
      "t\032+.com.br.estudos.grpc.RegisterMemberRe" +
      "sponse\022g\n\rregisterItens\022).com.br.estudos" +
      ".grpc.RegisterItensRequest\032).com.br.estu" +
      "dos.grpc.RegisterItemResponse(\001\022Y\n\013listM" +
      "embers\022\".com.br.estudos.grpc.MemberReque" +
      "st\032$.com.br.estudos.grpc.MembersResponse" +
      "0\001\022c\n\022voucherAndReceipts\022#.com.br.estudo" +
      "s.grpc.ReceiptRequest\032$.com.br.estudos.g" +
      "rpc.VoucherResponse(\0010\001\022L\n\013createEvent\022\"" +
      ".com.br.estudos.grpc.EventResquest\032\031.com" +
      ".br.estudos.grpc.VoidB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_br_estudos_grpc_RegisterMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_br_estudos_grpc_RegisterMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_RegisterMemberRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Phone", "EventName", });
    internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_br_estudos_grpc_RegisterMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor,
        new java.lang.String[] { "WelcomeMessage", });
    internal_static_com_br_estudos_grpc_RegisterItensRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_br_estudos_grpc_RegisterItensRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_RegisterItensRequest_descriptor,
        new java.lang.String[] { "Description", "Quantity", });
    internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_br_estudos_grpc_RegisterItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor,
        new java.lang.String[] { "TotalItensCreated", });
    internal_static_com_br_estudos_grpc_MembersResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_br_estudos_grpc_MembersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_MembersResponse_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Phone", });
    internal_static_com_br_estudos_grpc_MemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_br_estudos_grpc_MemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_MemberRequest_descriptor,
        new java.lang.String[] { "EventName", });
    internal_static_com_br_estudos_grpc_ReceiptRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_br_estudos_grpc_ReceiptRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_ReceiptRequest_descriptor,
        new java.lang.String[] { "Receipt", });
    internal_static_com_br_estudos_grpc_VoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_br_estudos_grpc_VoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_VoucherResponse_descriptor,
        new java.lang.String[] { "Voucher", });
    internal_static_com_br_estudos_grpc_EventResquest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_br_estudos_grpc_EventResquest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_EventResquest_descriptor,
        new java.lang.String[] { "EventName", });
    internal_static_com_br_estudos_grpc_Void_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_br_estudos_grpc_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_br_estudos_grpc_Void_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
