// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface ReceiptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.ReceiptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receipt = 1;</code>
   * @return The receipt.
   */
  java.lang.String getReceipt();
  /**
   * <code>string receipt = 1;</code>
   * @return The bytes for receipt.
   */
  com.google.protobuf.ByteString
      getReceiptBytes();
}
