// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

/**
 * Protobuf type {@code com.br.estudos.grpc.RegisterItemResponse}
 */
public  final class RegisterItemResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.br.estudos.grpc.RegisterItemResponse)
    RegisterItemResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterItemResponse.newBuilder() to construct.
  private RegisterItemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterItemResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterItemResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterItemResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalItensCreated_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterItemResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.br.estudos.grpc.RegisterItemResponse.class, com.br.estudos.grpc.RegisterItemResponse.Builder.class);
  }

  public static final int TOTALITENSCREATED_FIELD_NUMBER = 1;
  private int totalItensCreated_;
  /**
   * <code>int32 totalItensCreated = 1;</code>
   * @return The totalItensCreated.
   */
  public int getTotalItensCreated() {
    return totalItensCreated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalItensCreated_ != 0) {
      output.writeInt32(1, totalItensCreated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalItensCreated_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalItensCreated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.br.estudos.grpc.RegisterItemResponse)) {
      return super.equals(obj);
    }
    com.br.estudos.grpc.RegisterItemResponse other = (com.br.estudos.grpc.RegisterItemResponse) obj;

    if (getTotalItensCreated()
        != other.getTotalItensCreated()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALITENSCREATED_FIELD_NUMBER;
    hash = (53 * hash) + getTotalItensCreated();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterItemResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.br.estudos.grpc.RegisterItemResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.br.estudos.grpc.RegisterItemResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.br.estudos.grpc.RegisterItemResponse)
      com.br.estudos.grpc.RegisterItemResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterItemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.br.estudos.grpc.RegisterItemResponse.class, com.br.estudos.grpc.RegisterItemResponse.Builder.class);
    }

    // Construct using com.br.estudos.grpc.RegisterItemResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalItensCreated_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterItemResponse_descriptor;
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterItemResponse getDefaultInstanceForType() {
      return com.br.estudos.grpc.RegisterItemResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterItemResponse build() {
      com.br.estudos.grpc.RegisterItemResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterItemResponse buildPartial() {
      com.br.estudos.grpc.RegisterItemResponse result = new com.br.estudos.grpc.RegisterItemResponse(this);
      result.totalItensCreated_ = totalItensCreated_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.br.estudos.grpc.RegisterItemResponse) {
        return mergeFrom((com.br.estudos.grpc.RegisterItemResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.br.estudos.grpc.RegisterItemResponse other) {
      if (other == com.br.estudos.grpc.RegisterItemResponse.getDefaultInstance()) return this;
      if (other.getTotalItensCreated() != 0) {
        setTotalItensCreated(other.getTotalItensCreated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.br.estudos.grpc.RegisterItemResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.br.estudos.grpc.RegisterItemResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int totalItensCreated_ ;
    /**
     * <code>int32 totalItensCreated = 1;</code>
     * @return The totalItensCreated.
     */
    public int getTotalItensCreated() {
      return totalItensCreated_;
    }
    /**
     * <code>int32 totalItensCreated = 1;</code>
     * @param value The totalItensCreated to set.
     * @return This builder for chaining.
     */
    public Builder setTotalItensCreated(int value) {
      
      totalItensCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalItensCreated = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalItensCreated() {
      
      totalItensCreated_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.br.estudos.grpc.RegisterItemResponse)
  }

  // @@protoc_insertion_point(class_scope:com.br.estudos.grpc.RegisterItemResponse)
  private static final com.br.estudos.grpc.RegisterItemResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.br.estudos.grpc.RegisterItemResponse();
  }

  public static com.br.estudos.grpc.RegisterItemResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterItemResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterItemResponse>() {
    @java.lang.Override
    public RegisterItemResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterItemResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterItemResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterItemResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.br.estudos.grpc.RegisterItemResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

