// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.Void)
    com.google.protobuf.MessageOrBuilder {
}
