// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface EventResquestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.EventResquest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventName = 1;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <code>string eventName = 1;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();
}
