// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface RegisterItemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.RegisterItemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalItensCreated = 1;</code>
   * @return The totalItensCreated.
   */
  int getTotalItensCreated();
}
