// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface RegisterItensRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.RegisterItensRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
