// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface RegisterMemberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.RegisterMemberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string welcomeMessage = 1;</code>
   * @return The welcomeMessage.
   */
  java.lang.String getWelcomeMessage();
  /**
   * <code>string welcomeMessage = 1;</code>
   * @return The bytes for welcomeMessage.
   */
  com.google.protobuf.ByteString
      getWelcomeMessageBytes();
}
