// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

/**
 * Protobuf type {@code com.br.estudos.grpc.RegisterMemberResponse}
 */
public  final class RegisterMemberResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.br.estudos.grpc.RegisterMemberResponse)
    RegisterMemberResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterMemberResponse.newBuilder() to construct.
  private RegisterMemberResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterMemberResponse() {
    welcomeMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterMemberResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterMemberResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            welcomeMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterMemberResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.br.estudos.grpc.RegisterMemberResponse.class, com.br.estudos.grpc.RegisterMemberResponse.Builder.class);
  }

  public static final int WELCOMEMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object welcomeMessage_;
  /**
   * <code>string welcomeMessage = 1;</code>
   * @return The welcomeMessage.
   */
  public java.lang.String getWelcomeMessage() {
    java.lang.Object ref = welcomeMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      welcomeMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string welcomeMessage = 1;</code>
   * @return The bytes for welcomeMessage.
   */
  public com.google.protobuf.ByteString
      getWelcomeMessageBytes() {
    java.lang.Object ref = welcomeMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      welcomeMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWelcomeMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, welcomeMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWelcomeMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, welcomeMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.br.estudos.grpc.RegisterMemberResponse)) {
      return super.equals(obj);
    }
    com.br.estudos.grpc.RegisterMemberResponse other = (com.br.estudos.grpc.RegisterMemberResponse) obj;

    if (!getWelcomeMessage()
        .equals(other.getWelcomeMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WELCOMEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWelcomeMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.br.estudos.grpc.RegisterMemberResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.br.estudos.grpc.RegisterMemberResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.br.estudos.grpc.RegisterMemberResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.br.estudos.grpc.RegisterMemberResponse)
      com.br.estudos.grpc.RegisterMemberResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterMemberResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.br.estudos.grpc.RegisterMemberResponse.class, com.br.estudos.grpc.RegisterMemberResponse.Builder.class);
    }

    // Construct using com.br.estudos.grpc.RegisterMemberResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      welcomeMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.br.estudos.grpc.Barbecue.internal_static_com_br_estudos_grpc_RegisterMemberResponse_descriptor;
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterMemberResponse getDefaultInstanceForType() {
      return com.br.estudos.grpc.RegisterMemberResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterMemberResponse build() {
      com.br.estudos.grpc.RegisterMemberResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.br.estudos.grpc.RegisterMemberResponse buildPartial() {
      com.br.estudos.grpc.RegisterMemberResponse result = new com.br.estudos.grpc.RegisterMemberResponse(this);
      result.welcomeMessage_ = welcomeMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.br.estudos.grpc.RegisterMemberResponse) {
        return mergeFrom((com.br.estudos.grpc.RegisterMemberResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.br.estudos.grpc.RegisterMemberResponse other) {
      if (other == com.br.estudos.grpc.RegisterMemberResponse.getDefaultInstance()) return this;
      if (!other.getWelcomeMessage().isEmpty()) {
        welcomeMessage_ = other.welcomeMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.br.estudos.grpc.RegisterMemberResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.br.estudos.grpc.RegisterMemberResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object welcomeMessage_ = "";
    /**
     * <code>string welcomeMessage = 1;</code>
     * @return The welcomeMessage.
     */
    public java.lang.String getWelcomeMessage() {
      java.lang.Object ref = welcomeMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        welcomeMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string welcomeMessage = 1;</code>
     * @return The bytes for welcomeMessage.
     */
    public com.google.protobuf.ByteString
        getWelcomeMessageBytes() {
      java.lang.Object ref = welcomeMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        welcomeMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string welcomeMessage = 1;</code>
     * @param value The welcomeMessage to set.
     * @return This builder for chaining.
     */
    public Builder setWelcomeMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      welcomeMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string welcomeMessage = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWelcomeMessage() {
      
      welcomeMessage_ = getDefaultInstance().getWelcomeMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string welcomeMessage = 1;</code>
     * @param value The bytes for welcomeMessage to set.
     * @return This builder for chaining.
     */
    public Builder setWelcomeMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      welcomeMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.br.estudos.grpc.RegisterMemberResponse)
  }

  // @@protoc_insertion_point(class_scope:com.br.estudos.grpc.RegisterMemberResponse)
  private static final com.br.estudos.grpc.RegisterMemberResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.br.estudos.grpc.RegisterMemberResponse();
  }

  public static com.br.estudos.grpc.RegisterMemberResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterMemberResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterMemberResponse>() {
    @java.lang.Override
    public RegisterMemberResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterMemberResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterMemberResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterMemberResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.br.estudos.grpc.RegisterMemberResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

