// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barbecue.proto

package com.br.estudos.grpc;

public interface VoucherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.br.estudos.grpc.VoucherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string voucher = 1;</code>
   * @return The voucher.
   */
  java.lang.String getVoucher();
  /**
   * <code>string voucher = 1;</code>
   * @return The bytes for voucher.
   */
  com.google.protobuf.ByteString
      getVoucherBytes();
}
